### ISSUE TITLE
Use System.Numerics where applicable

### ISSUE THREAD

**Issue by HurricanKai** [ZacharyPatten/Towel#25]
For example Vectors are implemented in System.Numerics with intrinsics and everything, no point in reimplementing with worse performance

**Comment by ZacharyPatten** [comment]
I agree that System.Numerics is better for most applications, however it is limited. System.Numerics does not support decimal, BigInteger, BigRational, or any custom type. With the vectors in Towel, you can use any type inside them that have the necessary operator overloads. You can even use the scientific measurements types like "Acceleration" inside Towel's vectors. So there is still a use case.

As for using System.Numerics underneath my Towel vector when applicable, I have found that the overhead of making a System.Numeric vector is more than the benefit of the hardware intrinsics for individual mathematical operations. So although I would like to do that... I don't have a practical approach for it at the moment.

Please elaborate if you have know a way incorporate System.Numerics efficiently without compromising the support for other types.

**Comment by ZacharyPatten** [comment]
There is a very useful blog post here:
https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core/

**Comment by ZacharyPatten** [comment]
When doing generic programming... We need a way to convert a ReadOnlySpan<T> to a specific type suach as ReadOnlySpan<int>.

This is possible with the MemoryMarshal.Cast method.

With that (and the info from the link) I should have all the info I need to add hardware intrinsics to various parts of the Towel framework. :)

**Comment by ZacharyPatten** [comment]
I still want to pursue this topic, but I'm closing this issue as it does not point out any specific changes that can be made. Feel free to open more issues like this if you have ideas of specific changes.
