### ISSUE TITLE
Replace T[] with Memory<T> / Span<T>

### ISSUE THREAD

**Issue by HurricanKai** [ZacharyPatten/Towel#48]
Memory<T> / Span<T> are simply superior to T[] and cover almost the same uses.
I can't think of a reason to do this, besides that it is work. I'd be happy to PR these changes together with some Benchmarks showing the Performance (and usability) enhancements

**Comment by ZacharyPatten** [comment]
I would **love** to start using `Memory<T>` and `Span<T>` but they are not available in .NET Standard (it is .NET Core only). So I first need to migrate Towel to .NET Core. That will be easy, and I want to do so, but I have one example `CollisionDetection3D` that uses `OpenTK` which is currently not available for .NET Core. I need to re-implement the example using a .NET Core compatible dependency. I started writing my own Vulkan bindings (can be seen in the `Tools` folder), but I didn't get very far yet. There are existing libraries that have done so, and I might need to pull one of those in as a dependency for that example project.

**Comment by HurricanKai** [comment]
There is. You can install `System.Memory` and on .Net Standard 2.1 compatible runtimes it will be replaced by the built in ones, and else there are some a little slower software implementations.
Also, .Net Standard 2.1 > .Net Core 3

Regarding Bindings:
<https://github.com/terrafx/terrafx>
<https://github.com/Ultz/Silk.NET>

**Comment by ZacharyPatten** [comment]
If `Memory<T>` and `Span<T>` can be added to .NET Standard 2.0 then I'm game :) . I want to keep the dependencies to an absolute minimum, but `Span<T>` and `Memory<T>` are important and worth pulling in a dependency, and once Towel can get it moved to .NET Standard 2.1 (as you mentioned) it wouldn't need any dependency for it at that point.

I'll try to devote some time to migrating the `CollisionDetection3D` example into .NET Core. Being an example project (not part of the main source code) I don't care what library it uses for the graphics bindings. I haven't used Ultz or TerraFX enough to have a preference between them (and there are a lot of other C# Vulkan bindings on GitHub at the moment).

**Comment by HurricanKai** [comment]
I haven't really used either that much, and tbh I have no clue what the difference is, but yeah.
I'm testing out what some of the types could look like with Memory / Span. Looks like for most of them the change is quite easy.

**Comment by HurricanKai** [comment]
Benchmark for, for example, `ArrayList<int>.Add(1, 0)` N is the amount of times Added. As you can see, just converting T[] to Memory<T> / Span<T> improves performance everywhere, even on .Net FX 4.8 which doesn't support Memory/Span directly. (With some optimizations it could be even better)
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19569
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  Job-ZIIECU : .NET Framework 4.8 (4.8.4084.0), X64 RyuJIT
  Job-GPLSPK : .NET CoreRT 1.0.28702.01 @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: master @Commit: 65f1d8fb61c8d4d426562f8861a89bfd24b173b4, X64 AOT


```
|  Method |    Runtime |    N |           Mean |         Error |        StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |----------- |----- |---------------:|--------------:|--------------:|-------:|------:|------:|----------:|
| **Current** |   **.NET 4.8** |    **1** |       **9.821 ns** |     **0.0475 ns** |     **0.0444 ns** | **0.0387** |     **-** |     **-** |      **64 B** |
|     New |   .NET 4.8 |    1 |      30.766 ns |     0.4145 ns |     0.3878 ns | 0.0435 |     - |     - |      72 B |
| Current | CoreRt 3.1 |    1 |       8.962 ns |     0.0544 ns |     0.0482 ns | 0.0076 |     - |     - |      64 B |
|     New | CoreRt 3.1 |    1 |      19.703 ns |     0.1255 ns |     0.1173 ns | 0.0086 |     - |     - |      72 B |
| **Current** |   **.NET 4.8** |   **10** |     **149.116 ns** |     **1.4706 ns** |     **1.3756 ns** | **0.1690** |     **-** |     **-** |     **281 B** |
|     New |   .NET 4.8 |   10 |     379.486 ns |     5.0855 ns |     4.7570 ns | 0.1736 |     - |     - |     289 B |
| Current | CoreRt 3.1 |   10 |     148.551 ns |     2.4787 ns |     2.3186 ns | 0.0334 |     - |     - |     280 B |
|     New | CoreRt 3.1 |   10 |     178.857 ns |     2.1392 ns |     2.0010 ns | 0.0343 |     - |     - |     288 B |
| **Current** |   **.NET 4.8** |  **100** |   **4,417.628 ns** |    **69.5858 ns** |    **65.0906 ns** | **0.7477** |     **-** |     **-** |    **1252 B** |
|     New |   .NET 4.8 |  100 |   7,987.238 ns |    45.2585 ns |    42.3349 ns | 0.7477 |     - |     - |    1260 B |
| Current | CoreRt 3.1 |  100 |   4,514.785 ns |    52.5625 ns |    49.1670 ns | 0.1450 |     - |     - |    1248 B |
|     New | CoreRt 3.1 |  100 |   4,280.864 ns |    48.7082 ns |    45.5617 ns | 0.1450 |     - |     - |    1256 B |
| **Current** |   **.NET 4.8** | **1000** | **373,494.408 ns** | **1,268.9107 ns** | **1,186.9399 ns** | **4.8828** |     **-** |     **-** |    **8516 B** |
|     New |   .NET 4.8 | 1000 | 539,343.014 ns | 9,457.0295 ns | 8,846.1112 ns | 4.8828 |     - |     - |    8528 B |
| Current | CoreRt 3.1 | 1000 | 364,413.883 ns | 1,611.7861 ns | 1,507.6657 ns | 0.9766 |     - |     - |    8488 B |
|     New | CoreRt 3.1 | 1000 | 292,643.722 ns | 2,048.9294 ns | 1,816.3225 ns | 0.9766 |     - |     - |    8496 B |

**Comment by ZacharyPatten** [comment]
closing this as it is stale
