### ISSUE TITLE
Constant<T>.Pi requires GreaterThanOrEqual to be defined

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ZacharyPatten/Towel#55]
To be precise, in this line
```cs
pi = Maximum(pi, Constant<T>.Three);
```

It's better to first check whether the class has this operator defined, it's obviously unnecessary for this line, but it's called when Constant<T>.One is called.

My solution is presented in #56, but I don't think it fits the code quality requirements

**Comment by ZacharyPatten** [comment]
There is still more that will need to be done to the `ComputePi` method... But I went ahead and converted it to a property along with all the members of `Constant`. Using fields was faster than properties, but I've determined there are better ways to handle optimizations than worrying about the members of `Constant` being fields.

**Comment by WhiteBlackGoose** [comment]
It's a matter of a few nanoseconds, I don't think it's a big issue for those who use c#.
