### ISSUE TITLE
Static fields can be set outside?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ZacharyPatten/Towel#57]
For example
```cs
public static T Zero
{
    get
    {
        if (!_zero_assigned)
        {
            _zero = Convert<int, T>(0);
            _zero_assigned = true;
        }
 	return _zero;
    }
    set
    {
 	_zero = value;
 	_zero_assigned = true;
    }
}
```

Why do we need Zero and other constant field to be settable?

Also, to me it should look like:
```cs
private static T GetOrDefault<TDefault>(ref T field, ref bool assigned, TDefault value)
{
    if (!assigned)
    {
        field = Convert<TDefault, T>(value);
        assigned = true;
    }
    return field;
}

public static Zero => GetOrDefault(ref _zero, ref _zero_assigned, 0);
```

**Comment by ZacharyPatten** [comment]
The members of `Constant` do need to be settable/overridable. For example, I eventually want to use my `Symbolics.Expression` class with this code, and in that case I want `Constant<Symbolics.Expression>.Pi` to return `Symbolics.Pi`. That is a case where it would need to be set via the setter. I'm sure there are plenty of other use cases where people will want to change the constants for various reasons.

I do like your pattern though, that will clean up the source code a bit. I will keep the setter but apply the pattern you just mentioned. I coded that rather hastily without considering cleaner options.

**Comment by WhiteBlackGoose** [comment]
> want to use my Symbolics.Expression class with this code, and in that case I want Constant<Symbolics.Expression>.Pi to return Symbolics.Pi

Hmm, isn't it you who gave me a good advice for global settings? At least, if you ask me, setting a global static field for whatever reason doesn't sound as a good idea. Not only it's not thread safe (though it can be fixed easily), it's not safe at all if your other methods rely on this constant. Or you should manually revert it after every use.

**Comment by ZacharyPatten** [comment]
Other code relies on it yes, but there are certain situations where it is impossible for those constants to be assigned in my code. If I call `Constant<Symbolics.Expression>` on the current code, it would try to computer Pi as if it were a numeric value, when instead I want it to return an instance of a custom class, `Symbolics.Pi`. That is an example where allowing overriding is necessary.

People would need to set the constant before using any of the generic math operations with the relative type. This is a pretty advance feature/use-case that I wouldn't expect most people to use, but I still want to allow it.

**Comment by WhiteBlackGoose** [comment]
I see. Then, I think, you should make it depending on <T>. I'm right now working on my own Tensor library and my solution was smt like that:
```cs
var userType = new T();
userType.SetZero();
```
Where you run SetZero from your dynamic compilation thing. To me it's still better because it makes customization obvious (if you write documentation & samples of course)

**Comment by ZacharyPatten** [comment]
I personally prefer this:
```cs
Constant<MyType>.Pi = myValue;
```
Over this:
```cs
myValue.SetPi();
```
Because it is more explicit that it is setting the value in the Towel code.

But users are of course welcome to make that extension method if they want to.

Another option am I considering is allowing the values to be set via attribute on the type. I would keep the setters on the property but also look for the attribute before attempting a numerical computation.

**Comment by WhiteBlackGoose** [comment]
Okay, if it is intended...
