### ISSUE TITLE
Bad check for bounds

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ZacharyPatten/Towel#60]
this
```cs
Matrix<int> a = new int[,]
{
    {6,  1, 1},
    {4, -2, 5},
    {2,  8, 7}
};
Console.WriteLine(a[3, 3]);
```

leads to exception here in Get

```cs
return _matrix[row * Columns + column];
```

Because you should check it with >=, not >

```cs
get
{
    if (row < 0 || row >= /*NOT with >*/ Rows)
    {
        throw new ArgumentOutOfRangeException(nameof(row), row, "!(" + nameof(row) + " >= 0) || !(" + nameof(row) + " < " + nameof(Rows) + ")");
    }
    if (column < 0 || column >= /*NOT with >*/ Columns)
    {
        throw new ArgumentOutOfRangeException(nameof(column), row, "!(" + nameof(column) + " >= 0) || !(" + nameof(column) + " < " + nameof(Columns) + ")");
    }
    return Get(row, column);
}
```

same with set

**Comment by ZacharyPatten** [comment]
The row and column indceces are zero-based rather than one-based intentionally.

In your example you have a 3x3 matrix so the columns would be 0, 1 or 2.

**Comment by WhiteBlackGoose** [comment]
You didn't get. You wrote checks that should catch cases like this. But instead, your checks pass, but the exception is thrown when you address the linear array. What is worse, an exception won't be thrown in cases like `a[0, 3]`

**Comment by ZacharyPatten** [comment]
I'm dumb... Gotcha :D sorry. Yeah I'll fix that
