### ISSUE TITLE
Better get rid of "^" operator

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ZacharyPatten/Towel#62]
Unlike expected, it has a priority even lower than "+"

**Comment by ZacharyPatten** [comment]
I'm not sure what this issue is referring to. Can you elaborate?

**Comment by WhiteBlackGoose** [comment]
Erh, sorry. You override ^ operator for matrices, and as you know,
```
A + B ^ 2
```
is executed as (A + B) ^ 2 which would be hard to debug for users and they will have to think every time they use operators. So to keep it obvious I recommend to remove the ^ override

**Comment by ZacharyPatten** [comment]
I'm dumb. Agreed. I'm going to remove it. :)
