### ISSUE TITLE
Not a bug, just a question.

### ISSUE THREAD

**Issue by henon** [ZacharyPatten/Towel#70]
Hey Zach! 

Your code for loading XML comments in Towel is awesome. I don't want to pull in the whole Nuget though. Can I "borrow" this code for our MIT licensed open source blazor component library [MudBlazor](https://mudblazor.com) ?. We are using it to generate the documentation. Of course you'll be fully credited on our credits page and we'll link to this github repo.

Thanks man!

**Comment by ZacharyPatten** [comment]
Yes you may use it. :)

There are a couple of things I want to improve on it though (just to let you know). So there may be updates to it in the future. I haven't tested it with C#9 records yet, and there is another issue that I want to find a workaround for: https://github.com/ZacharyPatten/Towel/issues/52. But it works for the most use cases. If you notice any issues/improvements I would appreciate letting me know.

Regardless, good luck with your code.

**Comment by henon** [comment]
Thanks, you rock. Of course I'll push back fixes/issues if any.
