### ISSUE TITLE
There are identical sub-expressions 

### ISSUE THREAD

**Issue by thehlopster** [ZacharyPatten/Towel#76]
https://github.com/ZacharyPatten/Towel/blob/55df4c7a8ab4914a9380dc17cc346eed3f1ea287/Sources/Towel/CommandLine.cs#L85
it looks like copy paste error.

**Comment by ZacharyPatten** [comment]
agreed. I probably copy-pasted. thanks.

**Comment by ZacharyPatten** [comment]
fixed in #77 will be included in next nuget release
